### ISSUE TITLE
Create Course Service

### ISSUE THREAD

**Issue by JPautz** [cpe308-309/polypath#123]

**Comment by macrivello** [comment]
What's the status of this ?

**Comment by JPautz** [comment]
More or less in progress, the functionality we had for the demo obviously is there but the service isn't completely done. Same for #122 and #116

**Comment by JPautz** [comment]
I would argue for moving these to done, along with the other "create service" issues #122 and #116. From now on we could add issues such as "add X functionality to service Y". Thoughts?
