### ISSUE TITLE
Add Ability to Create Flowcharts

### ISSUE THREAD

**Issue by macrivello** [cpe308-309/polypath#129]
This should be a button in the sidebar component.

**Comment by BryceV** [comment]
Things to consider (that might be outside this sprint, break into sub issues if not covered):
- Make empty flowchart
- Make copy of existing flowchart
- Bring in a copy of a catalog flowchart

**Comment by BryceV** [comment]
There should be a limit because we are loading them all at once. Plus if this becomes hosted by Cal Poly, it prevents the system from being overwhelmed.
