### ISSUE TITLE
Change Flowchart Component to be a Pure Component

### ISSUE THREAD

**Issue by macrivello** [cpe308-309/polypath#150]
https://youtu.be/A4-bxyjXc40?t=27m32s

As described in the above video, pure components add important performance benefits regarding change detection, not to mention allowing them to be simpler and more testable. 

A pure component is like a pure function, given the same inputs, you will always get the same outputs. We can modify the flowchart component to take in the flowchart as an input variable.

Currently the grabs the flowchart from the flowchart service. The flowchart data should get passed in from somewhere else, most likely its parent.

**Comment by JPautz** [comment]
Does this go along the same idea as moving the flowchart below some top application component that resides just below the app-component?

Such as App Component -> Main application -> Flowchart?

**Comment by macrivello** [comment]
@JPautz precisely. I called it HomeComponent. You how I push up the observable one level from the flowchart component to the home component. https://github.com/macrivello/polypath/commit/184890c694377d4e47313eae6fd1b92fa4be9282

**Comment by JPautz** [comment]
Cool cool, I like it. Was definitely something that was causing issues before not having it

**Comment by JPautz** [comment]
Difference between this and #151 ?

**Comment by JPautz** [comment]
Lol the other is a pull request nvm
