### ISSUE TITLE
Allow empty quarter views to be displayed on flowchart.

### ISSUE THREAD

**Issue by macrivello** [cpe308-309/polypath#160]
If a course does not exist in a quarter, the quarter still shows up in the flowchart. We need to allow a quarter to still show if there are no courses are in it. @BryceV @mpjimenez and I talked about showing quarters in a collapsed state when they are empty.

**Comment by JPautz** [comment]
Yeah, I think showing in a collapsed state would be perfect

**Comment by macrivello** [comment]
I've also implemented flowcharts defaulting being 4 years (16 quarters).

**Comment by JPautz** [comment]
Is this issue complete then at this point @macrivello ?
