### ISSUE TITLE
Make a admin page wirewframe

### ISSUE THREAD

**Issue by JPautz** [cpe308-309/polypath#163]
Design a UI wireframe to act as a model during development

**Comment by BryceV** [comment]
6 files (one xml paired with png): "PolyPathStudentFlowchartPage", "PolyPathAdminFlowchartPage",  and "PolyPathAdminAnalyticsPage" . Located on https://drive.google.com/drive/folders/0B-cmdHnGrTOuQlhjejdTREJhMXM
