### ISSUE TITLE
Remove duplicate courses in course search

### ISSUE THREAD

**Issue by BryceV** [cpe308-309/polypath#185]

**Comment by JPautz** [comment]
There are duplicates in the table, this was discovered when searching to add CPE 357 to a flowchart. I think this exists because I had added courses then @macrivello loaded the rest from the other teams JSON. This I believe created duplicates. Will investigate further, should be easy fix.

**Comment by JPautz** [comment]
False alarm, they were cross listed courses (CSC vs CPE), nothing needing to be fixed here.
