### ISSUE TITLE
Create account for professor Socher

### ISSUE THREAD

**Issue by mpjimenez** [cpe308-309/polypath#186]

**Comment by JPautz** [comment]
@gsocher I'll get working on making you youre own but you can log in 
as a student with jpautz@calpoly.edu : password2
as an admin with staff@calpoly.edu : staff

**Comment by JPautz** [comment]
@gsocher  issue complete see commit below
https://github.com/cpe308-309/polypath/commit/a83b30e29b5950a90ab88e17dd27dfc7ff22e8a9
