### ISSUE TITLE
Create a basic flowchart page

### ISSUE THREAD

**Issue by m-duran** [cpe308-309/polypath#43]
Create a basic static page of the structure of the flowchart. 
It should include four years with four quarters each.

**Comment by macrivello** [comment]
https://v4-alpha.getbootstrap.com/

**Comment by BryceV** [comment]
I also put the bootstrap CDN at the top of my log in page. Maybe we can import it so that it can be used by all webpages?

**Comment by m-duran** [comment]
Probably shouldn't have closed it yet..
