### ISSUE TITLE
Create Course Search View

### ISSUE THREAD

**Issue by macrivello** [cpe308-309/polypath#45]
We want a view component to be able to search for courses to be added to a flowchart.

**Comment by macrivello** [comment]
See #46

**Comment by JPautz** [comment]
Take from courses page we have now (index.html) and add search functionality. Remove create/update/delete functionality. User should be able to search in a search bar and possible matches will be listed. User can then select a course from that list and click an add button to add it to the flowchart. This add button will not have functionality until we merge all the code so don't bother trying to implement.

**Comment by BryceV** [comment]
See #97

**Comment by macrivello** [comment]
Closing this issue, duplicate of #97
