### ISSUE TITLE
Update Class Diagram to Include FlowchartEntry class

### ISSUE THREAD

**Issue by macrivello** [cpe308-309/polypath#51]

**Comment by BryceV** [comment]
https://github.com/cpe308-309/AvengersRepo/blob/master/docs/MasterUMLClassDiagram.png

**Comment by BryceV** [comment]
https://github.com/cpe308-309/AvengersRepo/blob/master/docs/MasterUMLClassDiagram.xml

**Comment by JPautz** [comment]
I dont think this is done....what we had previously needed to be tweaked. If you believe it is done please post a link to the image.

**Comment by JPautz** [comment]
Updated diagrams see 
commit https://github.com/cpe308-309/polypath/commit/b61fe62648f45730d70055e269ef3d1f31dd0ff4
https://drive.google.com/drive/folders/0B-cmdHnGrTOuTkxIYTkwMlVzZWs
