### ISSUE TITLE
Setup SonarQube for usage during CPE 309

### ISSUE THREAD

**Issue by mpjimenez** [cpe308-309/polypath#79]

**Comment by JPautz** [comment]
Is this issue complete? I don't see a comment thread or reference to files etc.

**Comment by macrivello** [comment]
Here's the sonarqube project link: https://sonarqube.com/dashboard?id=edu.calpoly.cpe%3Apolypath%3Aangular

**Comment by macrivello** [comment]
So yes, I think it's complete.
