### ISSUE TITLE
Create Course-Search Component

### ISSUE THREAD

**Issue by JPautz** [cpe308-309/polypath#97]

**Comment by BryceV** [comment]
see #45

**Comment by macrivello** [comment]
Copying from #45 Take from courses page we have now (index.html) and add search functionality. Remove create/update/delete functionality. User should be able to search in a search bar and possible matches will be listed. User can then select a course from that list and click an add button to add it to the flowchart. This add button will not have functionality until we merge all the code so don't bother trying to implement.

**Comment by m-duran** [comment]
I'm having trouble getting data back for "api/courses", don't know why.

**Comment by macrivello** [comment]
What's the http response code you're getting? Any server side logs?

**Comment by m-duran** [comment]
It ended up being something dumb like I wasn't accessing the data right. I don't remember, it was late at night.
